# Site settings
name: Dafuny
description: "Nothing to share"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  dafuny
weibo_username: dafuney
blog_url: "https://blog.csdn.net/qq_35045096"
email: yuefurong97@gmail.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1573619420136&di=7618023dd2306f94864d268c38ccadf8&imgtype=0&src=http%3A%2F%2Fi0.hdslb.com%2Fbfs%2Farticle%2F5c879977f46e404d9df277d1cdcfd0c073918167.png"


front_img: yes
front_img_path: "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1573619627453&di=8f8839e4cad464090dce2f20f81577d8&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2Fb82b41a6c63ef989082965768e212a92ffaee38630ae-ZouRgw_fw658"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
